[macro]
;;;;; AutoNet macros ;;;;;
; Replace NETNODE with the target net node number. Also don't paste the macro header it's just to help you identify where this section goes.

1 = *901                    ; Play 10-minute warning
2 = *902                    ; Play 5-minute warning
3 = *903*806*3NETNODE       ; Play "now", disconnect all, connect to net
4 = *1NETNODE*816           ; Leave net and restore previous links
